# Site
name: "Turing"
title: "Turing"
description: "Tons of algorithms"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: "/Turing"
google_analytics: 'UA-46278016-1'
disqus: 'https-5arthak01-github-io-turing'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  # sal:
  #   name: Sal
  #   display_name: Sal
  #   gravatar: e56154546cf4be74e393c62d1ae9f9d4
  #   email: wowthemesnet@gmail.com
  #   web: https://www.wowthemes.net
  #   twitter: https://twitter.com/wowthemesnet
  #   description: "Author of Mediumish, a Bootstrap Medium styled template available for WordPress, HTML, Ghost and Jekyll. You are currently previewing Jekyll template demo."
  # john:
  #   name: John
  #   display_name: John    
  #   avatar: 'assets/images/avatar.png'
  #   gravatar: b1cc14991db7a456fcd761680bbc8f81
  #   email: wowthemesnet@gmail.com
  #   web: https://www.wowthemes.net
  #   twitter: https://twitter.com/wowthemesnet
  #   description: "This is the author box. Write a short description of the author here. You are currently previewing Mediumish demo, a Jekyll template compatible with Github pages."
  abhi:
    name: Abhijeeth Singam
    display_name: Abhi
    gravatar: 9174e0b922aa2746766beb65425721e6
    email: abhijeeth.singam@students.iiit.ac.in
    web: https://github.com/AbhiSingam/
    description: "Hi, I'm Abhijeeth. I'm a student at the International Institute of Information Technology - Hyderabad. I'm currently studying Computer Science and expect to graduate in 2023."
  Aadarsh:
    name: Aadarsh Raghunathan
    display_name: Aadarsh
    avatar: 'assets/images/avatar.png'
    email: aadarsh.raghunathan@research.iiit.ac.in
    web: https://github.com/aadarshraghunathan/
    description: "Hi, I'm Aadarsh. I'm a student at the International Institute of Information Technology - Hyderabad. I'm currently studying Computational Natural Science and expect to graduate in 2024."
  Sarthak:
    name: Sarthak Agrawal
    display_name: Sarthak
    avatar: 'assets/images/avatar.png'
    email: sarthak.agrawal@research.iiit.ac.in
    web: https://github.com/5arthak01/
    description: "Hi! I'm Sarthak - a CS undergrad at IIIT-H and CSGO fanatic."
  Tushar:
    name: Tushar Jain
    display_name: Tushar
    avatar: 'assets/images/avatar.png'
    email: tushar.j@students.iiit.ac.in
    web: https://github.com/tushar994
    description: "Hi, I'm Tushar. I study CSE at International Institute of Information Technology - Hyderabad"
  Ainesh:
    name: Ainesh Sannidhi
    display_name: Ainesh
    avatar: 'assets/images/avatar.png'
    email: ainesh.sannidhi@students.iiit.ac.in
    web: https://github.com/inesane
    description: "Hi, I'm Ainesh. I am currently a sophomore CSE undergrad at the International Institute of Information Technology - Hyderabad"
  Rishabh:
    name: Rishabh Khanna
    display_name: Rishabh
    avatar: 'assets/images/avatar.png'
    email: rishabh.khanna@students.iiit.ac.in
    web: https://github.com/KyaBacchaHai
    description: "Hi, I'm Rishabh. I am currently a sophomore Computational Natural Sciences undergrad at the International Institute of Information Technology - Hyderabad"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [_exclude, changelog.md, LICENSE, wowthemesnet_license.md, README.md, Gemfile, Gemfile.lock, .gitignore]

# Build settings
markdown: kramdown
